sudo: required
services: docker
os: linux
dist: xenial
  
language: c
before_script:
  - test -d m4 || mkdir m4
  - docker build -n test .
script: docker run test
addons:
  apt:
    packages:
      - gcc
      - automake
      - lcov
      - libtool
      - libdmalloc-dev
      - libcurl4-openssl-dev
      - curl
      - perl
      - valgrind
      - libtest-pod-perl
#  srcclr: true
