sudo: required
services: docker
os: linux
dist: xenial
before_install:
  - docker pull ubuntu:latest
  
language: c
before_script:
  - test -d m4 || mkdir m4
  - docker run -n temp ubuntu:latest sh -c 'apt-get -qq -y update && DEBIAN_FRONTEND=noninteractive apt-get -qq -y dist-upgrade && DEBIAN_FRONTEND=noninteractive apt-get -qq -y install autoconf-archive automake build-essential curl gcc git lcov libcurl4-openssl-dev libdmalloc-dev libpthread-stubs0-dev libtest-pod-perl libtool perl pkg-config python-pip valgrind && pip install --upgrade pip && pip install cpp-coveralls'
script: docker run -n test temp sh -c '(cd c-tap-harness && ./bootstrap) && autoreconf -i && ./configure --enable-valgrind --enable-compiler-warnings=error --with-dmalloc --with-gcov && make distcheck'
#COPY . /root/dial-reference

addons:
  apt:
    packages:
      - gcc
      - automake
      - lcov
      - libtool
      - libdmalloc-dev
      - libcurl4-openssl-dev
      - curl
      - perl
      - valgrind
      - libtest-pod-perl
  srcclr: true
