sudo: false
language: c
before_script:
  - test -d m4 || mkdir m4
  - pip install --user cpp-coveralls
script: (cd c-tap-harness && ./bootstrap) && autoreconf -i && ./configure && make && make check
addons:
  apt:
    packages:
      - gcc
      - automake
      - libtool
      - libdmalloc-dev
      - libcurl-dev
      - curl
      - pod2man
  srcclr: true
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: yakkety
